"""PDF generation pipeline: TWI text → Jinja2 HTML → WeasyPrint PDF bytes."""

import re
from datetime import datetime, timezone

import markdown as md
from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML

_template_env = Environment(
    loader=FileSystemLoader("app/templates"),
    autoescape=False,  # HTML is trusted — generated by the system
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _extract_title(content: str) -> str:
    """Extract the first meaningful line from the TWI draft as the document title."""
    for line in content.split("\n"):
        clean = line.strip().lstrip("#").strip()
        if clean and not clean.startswith("⚠️"):
            return clean[:100]
    return "TWI Munkautasítás"


async def generate_twi_pdf(
    content: str,
    metadata: dict,
    user_id: str,
    approval_timestamp: str | None = None,
) -> bytes:
    """Convert a TWI draft string into a formatted A4 PDF.

    Args:
        content: The full TWI markdown text (including EU AI Act label).
        metadata: Draft metadata dict (model, generated_at, revision).
        user_id: The approving user's ID shown in the approval box.
        approval_timestamp: ISO 8601 approval timestamp, or None.

    Returns:
        PDF as raw bytes.
    """
    # Markdown → HTML (supports fenced code blocks and tables)
    content_html = md.markdown(content, extensions=["tables", "fenced_code"])

    approved_at = (
        approval_timestamp
        or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    )

    template = _template_env.get_template("twi_template.html")
    html_content = template.render(
        title=_extract_title(content),
        generated_at=metadata.get("generated_at", "N/A"),
        model=metadata.get("model", "N/A"),
        revision=metadata.get("revision", 0),
        content_html=content_html,
        approved=True,
        approved_by=user_id,
        approved_at=approved_at,
    )

    pdf_bytes: bytes = HTML(string=html_content).write_pdf()
    return pdf_bytes
